'use client';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { Button } from "../components/ui/button";
import { dark } from '@clerk/themes';
import { HeaderAuthButtons } from "../components/header-auth-buttons";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <header className="relative flex items-center justify-center p-4 bg-gray-100 bg-opacity-95 shadow-md text-foreground border-b">
              <h1 className="text-xl font-bold mb-4 sm:mb-0 text-black">Flashy Cards</h1>
              <div className="absolute right-4 top-1/2 -translate-y-1/2 flex items-center gap-4">
                <HeaderAuthButtons />
              </div>
            </header>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
