'use client';

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from '@clerk/themes';
import { HeaderAuthButtons } from "../components/header-auth-buttons";
import { MobileNav } from "../components/mobile-nav";
import { ThemeToggle } from "../components/theme-toggle";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider 
      appearance={{
        baseTheme: undefined, // Let Clerk auto-detect based on system theme
        elements: {
          formButtonPrimary: 'bg-primary text-primary-foreground hover:bg-primary/90',
          card: 'bg-card border border-border',
          headerTitle: 'text-foreground',
          headerSubtitle: 'text-muted-foreground',
          socialButtonsBlockButton: 'bg-background border border-border text-foreground hover:bg-accent',
          formFieldLabel: 'text-foreground',
          formFieldInput: 'bg-background border border-border text-foreground',
          footerActionLink: 'text-primary hover:text-primary/80',
          dividerLine: 'bg-border',
          dividerText: 'text-muted-foreground',
          userButtonAvatarBox: 'border-2 border-border',
          userButtonPopoverCard: 'bg-card border border-border shadow-lg',
          userButtonPopoverActionButton: 'text-foreground hover:bg-accent',
        }
      }}
    >
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 header-pattern">
              <div className="container mx-auto px-3 sm:px-4 lg:px-8">
                <div className="flex h-12 sm:h-14 lg:h-16 items-center justify-between">
                  {/* Logo and Brand */}
                  <div className="flex items-center space-x-2 sm:space-x-3 lg:space-x-4 min-w-0">
                    <Link href="/" className="flex items-center space-x-1 sm:space-x-2 group min-w-0">
                      <div className="flex h-6 w-6 sm:h-7 sm:w-7 lg:h-8 lg:w-8 items-center justify-center rounded-lg bg-black dark:bg-white text-white dark:text-black font-bold text-sm sm:text-base lg:text-lg shadow-lg group-hover:shadow-xl group-hover:scale-105 transition-all duration-300 flex-shrink-0">
                        F
                      </div>
                      <span className="text-base sm:text-lg lg:text-xl font-bold text-foreground group-hover:text-muted-foreground transition-all duration-300 truncate">
                        <span className="hidden xs:inline">Flashy Cards</span>
                        <span className="xs:hidden">Flashy</span>
                      </span>
                    </Link>
                  </div>

                  {/* Navigation Links */}
                  <nav className="hidden lg:flex items-center space-x-6">
                    <Link 
                      href="/dashboard" 
                      className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors duration-200 hover:scale-105 transform"
                    >
                      Dashboard
                    </Link>
                    <Link 
                      href="/pricing" 
                      className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors duration-200 hover:scale-105 transform"
                    >
                      Pricing
                    </Link>
                    <Link 
                      href="/about" 
                      className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors duration-200 hover:scale-105 transform"
                    >
                      About
                    </Link>
                    <Link 
                      href="/help" 
                      className="text-sm font-medium text-muted-foreground hover:text-foreground transition-colors duration-200 hover:scale-105 transform"
                    >
                      Help
                    </Link>
                  </nav>

                  {/* Auth Buttons and Mobile Nav */}
                  <div className="flex items-center space-x-1 sm:space-x-2 lg:space-x-4">
                    <div className="hidden sm:block">
                      <ThemeToggle />
                    </div>
                    <MobileNav />
                    <HeaderAuthButtons />
                  </div>
                </div>
              </div>
            </header>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
